default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
    rev: v0.3.7
    hooks:
      # Run the linter.
      - id: ruff
        types: [python]
        args: [ --fix, --select, I]
      # Run the formatter.
      - id: ruff-format
        entry: bash -c 'cd backend'
        files: ^backend/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        types: [python]
        args: [ 
        --python-version=3.10,
        --strict,
        --disable-error-code=import-untyped,
        --disable-error-code=no-any-return,
        --ignore-missing-imports,
        --allow-untyped-decorators,
        --allow-subclassing-any,
        --implicit-reexport
        ]
        entry: bash -c 'cd backend'
        files: ^backend/

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v7.32.0'
    hooks:
      - id: eslint
        types: [file]
        types_or: [javascript, jsx, ts, tsx, vue]
        additional_dependencies:
        - eslint-plugin-vue@8.0.3
        args: [
        --fix
        ]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v4.0.0-alpha.8'  
    hooks:
      - id: prettier
        types: [file]
        types_or: [javascript, jsx, ts, tsx, vue]
        args: [
        --cache-location,
        "./frontend/node_modules/.cache/prettier/.prettier-cache",
        --arrow-parens,
         "avoid" ,
        --jsx-single-quote,
        --print-width,
         "120",
        --single-attribute-per-line,
        --single-quote,
        --tab-width,
         "4",
        --vue-indent-script-and-style,
        --write, 
        "./**/*.{js,vue,html,css}"
        ]

