default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
    rev: v0.3.7
    hooks:
      # Run the linter.
      - id: ruff
        types: [python]
        args: [ --fix, --select, I]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        types: [python]
        args: [ 
        --python-version=3.10,
        --strict,
        --disable-error-code=import-untyped,
        --disable-error-code=no-any-return,
        --ignore-missing-imports,
        --allow-untyped-decorators,
        --allow-subclassing-any,
        --implicit-reexport
        ]