"""initial_revision

Revision ID: 0f26e43206a7
Revises: 
Create Date: 2024-01-11 18:56:00.233175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f26e43206a7'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'service',
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('duration', sa.Integer(), nullable=False),
        sa.Column('uuid', sa.UUID(), nullable=False),
        sa.Column(
            'created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column(
            'updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
        ),
        sa.PrimaryKeyConstraint('uuid'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'user',
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('hashed_password', sa.String(length=60), nullable=False),
        sa.Column('username', sa.String(length=20), nullable=False),
        sa.Column('confirmed', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('confirmed_on', sa.DateTime(timezone=True), nullable=True),
        sa.Column('active', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('admin', sa.Boolean(), nullable=False),
        sa.Column('uuid', sa.UUID(), nullable=False),
        sa.Column(
            'created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column(
            'updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
        ),
        sa.PrimaryKeyConstraint('uuid'),
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table(
        'entry',
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('time', sa.Time(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('completed', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('uuid', sa.UUID(), nullable=False),
        sa.Column(
            'created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column(
            'updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
        ),
        sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('uuid'),
    )
    op.create_table(
        'post',
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('image', sa.String(length=50), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('author_id', sa.UUID(), nullable=False),
        sa.Column('uuid', sa.UUID(), nullable=False),
        sa.Column(
            'created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column(
            'updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
        ),
        sa.ForeignKeyConstraint(['author_id'], ['user.uuid'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('uuid'),
        sa.UniqueConstraint('title'),
    )
    op.create_table(
        'social',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('avatar', sa.String(length=50), nullable=False),
        sa.Column('first_name', sa.String(length=50), nullable=True),
        sa.Column('last_name', sa.String(length=50), nullable=True),
        sa.Column('phone_number', sa.String(length=50), nullable=True),
        sa.Column('viber', sa.String(length=50), nullable=True),
        sa.Column('whatsapp', sa.String(length=50), nullable=True),
        sa.Column('instagram', sa.String(length=255), nullable=True),
        sa.Column('telegram', sa.String(length=255), nullable=True),
        sa.Column('youtube', sa.String(length=255), nullable=True),
        sa.Column('website', sa.String(length=255), nullable=True),
        sa.Column('vk', sa.String(length=255), nullable=True),
        sa.Column('about', sa.String(length=255), nullable=True),
        sa.Column('uuid', sa.UUID(), nullable=False),
        sa.Column(
            'created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column(
            'updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
        ),
        sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('uuid'),
        sa.UniqueConstraint('instagram'),
        sa.UniqueConstraint('phone_number'),
        sa.UniqueConstraint('telegram'),
        sa.UniqueConstraint('viber'),
        sa.UniqueConstraint('vk'),
        sa.UniqueConstraint('website'),
        sa.UniqueConstraint('whatsapp'),
        sa.UniqueConstraint('youtube'),
    )
    op.create_table(
        'association_table',
        sa.Column('entry_id', sa.UUID(), nullable=True),
        sa.Column('service_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['entry_id'], ['entry.uuid'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['service_id'], ['service.uuid'], ondelete='SET NULL'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_table')
    op.drop_table('social')
    op.drop_table('post')
    op.drop_table('entry')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('service')
    # ### end Alembic commands ###
