"""added onupdate cascade

Revision ID: 8e294ff68dda
Revises: 0f26e43206a7
Create Date: 2024-04-07 12:16:51.465075

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = '8e294ff68dda'
down_revision = '0f26e43206a7'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('entry_user_id_fkey', 'entry', type_='foreignkey')
    op.create_foreign_key(
        'entry_user_id_fkey', 'entry', 'user', ['user_id'], ['uuid'], onupdate='CASCADE', ondelete='CASCADE'
    )
    op.drop_constraint('post_author_id_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(
        'post_author_id_fkey', 'post', 'user', ['author_id'], ['uuid'], onupdate='CASCADE', ondelete='CASCADE'
    )
    op.drop_constraint('social_user_id_fkey', 'social', type_='foreignkey')
    op.create_foreign_key(
        'social_user_id_fkey', 'social', 'user', ['user_id'], ['uuid'], onupdate='CASCADE', ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('social_user_id_fkey', 'social', type_='foreignkey')
    op.create_foreign_key('social_user_id_fkey', 'social', 'user', ['user_id'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint('post_author_id_fkey', 'post', type_='foreignkey')
    op.create_foreign_key('post_author_id_fkey', 'post', 'user', ['author_id'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint('entry_user_id_fkey', 'entry', type_='foreignkey')
    op.create_foreign_key('entry_user_id_fkey', 'entry', 'user', ['user_id'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###
