"""added werty

Revision ID: 108fe7a4e103
Revises: 9c6cc7609675
Create Date: 2023-07-10 17:12:30.288619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108fe7a4e103'
down_revision = '9c6cc7609675'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=60), nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
