"""Added services and entries tables

Revision ID: 489f039be824
Revises: a04b6c486a54
Create Date: 2024-01-04 11:48:29.789341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489f039be824'
down_revision = 'a04b6c486a54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('duration', sa.Numeric(scale=1), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('entry',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('association_table',
    sa.Column('entry_id', sa.UUID(), nullable=True),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['service.uuid'], ondelete='SET NULL')
    )
    op.alter_column('post', 'image',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint(None, 'post', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='unique')
    op.alter_column('post', 'image',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_table('association_table')
    op.drop_table('entry')
    op.drop_table('service')
    # ### end Alembic commands ###
