"""Added completed field to entry model

Revision ID: 64d4fe336109
Revises: 489f039be824
Create Date: 2024-01-05 05:34:19.393700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64d4fe336109'
down_revision = '489f039be824'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('completed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'completed')
    # ### end Alembic commands ###
