"""Added social table

Revision ID: 9b037c07f3f1
Revises: fa5dedf638e2
Create Date: 2023-12-31 05:47:37.353472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b037c07f3f1'
down_revision = 'fa5dedf638e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'social',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('avatar', sa.String(length=20), nullable=False),
        sa.Column('first_name', sa.String(length=50), nullable=True),
        sa.Column('last_name', sa.String(length=50), nullable=True),
        sa.Column('phone_number', sa.String(length=50), nullable=True),
        sa.Column('viber', sa.String(length=50), nullable=True),
        sa.Column('whatsapp', sa.String(length=50), nullable=True),
        sa.Column('instagram', sa.String(length=255), nullable=True),
        sa.Column('telegram', sa.String(length=255), nullable=True),
        sa.Column('youtube', sa.String(length=255), nullable=True),
        sa.Column('website', sa.String(length=255), nullable=True),
        sa.Column('vk', sa.String(length=255), nullable=True),
        sa.Column('about', sa.String(length=255), nullable=True),
        sa.Column('uuid', sa.UUID(), nullable=False),
        sa.Column(
            'created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column(
            'updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
        ),
        sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('uuid'),
        sa.UniqueConstraint('instagram'),
        sa.UniqueConstraint('phone_number'),
        sa.UniqueConstraint('telegram'),
        sa.UniqueConstraint('viber'),
        sa.UniqueConstraint('vk'),
        sa.UniqueConstraint('website'),
        sa.UniqueConstraint('whatsapp'),
        sa.UniqueConstraint('youtube'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social')
    # ### end Alembic commands ###
